{{- if .Values.rcodezeroApiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: gandi-credentials
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cert-manager-webhook-gandi.labels" . | nindent 4 }}
type: Opaque
data:
  api-token: {{ .Values.rcodezeroApiToken | toString | b64enc | quote }}
{{- end }}