{{- if .Values.rcodezeroApiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: rcodezero-api-token
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "certmanager-webhook-rcodezero.labels" . | nindent 4 }}
type: Opaque
data:
  api-token: {{ .Values.rcodezeroApiToken | toString | b64enc | quote }}
{{- end }}